// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using smartApi.Data;

#nullable disable

namespace smartApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("smartApi.Entity.LoginActivity", b =>
                {
                    b.Property<long>("LoginActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LoginActivityId"));

                    b.Property<string>("AttemptedIdentifier")
                        .HasColumnType("text");

                    b.Property<string>("BrowserName")
                        .HasColumnType("text");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DeviceType")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FailureCode")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<Guid?>("LoginChallengeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperatingSystem")
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<long?>("UserDeviceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("UserSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginActivityId");

                    b.HasIndex("LoginChallengeId");

                    b.HasIndex("UserDeviceId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserSessionId");

                    b.ToTable("LoginActivities");
                });

            modelBuilder.Entity("smartApi.Entity.LoginChallenge", b =>
                {
                    b.Property<Guid>("LoginChallengeId")
                        .HasColumnType("uuid")
                        .HasColumnName("login_challenge_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("LastOtpSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_otp_sent_at");

                    b.Property<int>("ResendCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("resend_count");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("revoked_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("LoginChallengeId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_login_challenges_expires_at");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_login_challenges_status_expires_at");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_login_challenges_user_id_status");

                    b.ToTable("login_challenges", (string)null);
                });

            modelBuilder.Entity("smartApi.Entity.RefreshToken", b =>
                {
                    b.Property<long>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("refresh_token_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RefreshTokenId"));

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<DateTime>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("ReplacedByTokenId")
                        .HasColumnType("bigint")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("revoked_by_ip");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("revoked_reason");

                    b.Property<string>("TokenFamilyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("token_family_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("UserSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_session_id");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_refresh_tokens_expires_at");

                    b.HasIndex("ReplacedByTokenId");

                    b.HasIndex("RevokedAt")
                        .HasDatabaseName("idx_refresh_tokens_revoked_at");

                    b.HasIndex("TokenFamilyId")
                        .HasDatabaseName("idx_refresh_tokens_family");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("uq_refresh_tokens_token_hash");

                    b.HasIndex("UserSessionId")
                        .HasDatabaseName("idx_refresh_tokens_user_session");

                    b.HasIndex("TokenHash", "ExpiresAt")
                        .HasDatabaseName("idx_refresh_tokens_token_lookup");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("idx_refresh_tokens_user_expiry");

                    b.HasIndex("UserId", "IsRevoked")
                        .HasDatabaseName("idx_refresh_tokens_user_active");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("smartApi.Entity.Role", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystemRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_system_role");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "System administrator with full access",
                            IsSystemRole = true,
                            RoleName = "ADMIN"
                        },
                        new
                        {
                            RoleId = 2L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default normal user role",
                            IsSystemRole = true,
                            RoleName = "USER"
                        },
                        new
                        {
                            RoleId = 3L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manager role with limited administrative access",
                            IsSystemRole = true,
                            RoleName = "MANAGER"
                        },
                        new
                        {
                            RoleId = 4L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Support role for customer or user assistance",
                            IsSystemRole = true,
                            RoleName = "SUPPORT"
                        });
                });

            modelBuilder.Entity("smartApi.Entity.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("account_status");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<int>("FailedLoginCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_count");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<int>("SecurityVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("smartApi.Entity.UserCredential", b =>
                {
                    b.Property<long>("CredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("credential_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CredentialId"));

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("must_change_password");

                    b.Property<string>("PasswordAlgorithm")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("BCrypt")
                        .HasColumnName("password_algorithm");

                    b.Property<DateTime>("PasswordCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_salt");

                    b.Property<DateTime?>("PasswordUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("CredentialId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_credentials", (string)null);
                });

            modelBuilder.Entity("smartApi.Entity.UserDevice", b =>
                {
                    b.Property<long>("UserDeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_device_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserDeviceId"));

                    b.Property<string>("BrowserName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("browser_name");

                    b.Property<string>("BrowserVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("browser_version");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("DeactivationReason")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("deactivation_reason");

                    b.Property<string>("DeviceFingerprintHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("device_fingerprint_hash");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("device_name");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("UNKNOWN")
                        .HasColumnName("device_type");

                    b.Property<DateTime>("FirstSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsTrusted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_trusted");

                    b.Property<string>("LastIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("last_ip_address");

                    b.Property<DateTime>("LastSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("LastUserAgent")
                        .HasColumnType("text")
                        .HasColumnName("last_user_agent");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operating_system");

                    b.Property<string>("OperatingSystemVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("operating_system_version");

                    b.Property<DateTime?>("TrustExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trust_expires_at");

                    b.Property<DateTime?>("TrustRevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trust_revoked_at");

                    b.Property<string>("TrustRevokedReason")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("trust_revoked_reason");

                    b.Property<DateTime?>("TrustedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trusted_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("UserDeviceId");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("idx_user_devices_last_seen");

                    b.HasIndex("TrustExpiresAt")
                        .HasDatabaseName("idx_user_devices_trust_expiry");

                    b.HasIndex("UserId", "DeviceFingerprintHash")
                        .IsUnique()
                        .HasDatabaseName("uq_user_devices_user_fingerprint");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("idx_user_devices_user_active");

                    b.HasIndex("UserId", "IsTrusted")
                        .HasDatabaseName("idx_user_devices_user_trusted");

                    b.ToTable("user_devices", (string)null);
                });

            modelBuilder.Entity("smartApi.Entity.UserRole", b =>
                {
                    b.Property<long>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserRoleId"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("AssignedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<long?>("RevokedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("revoked_by_user_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("UserRoleId");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("RevokedByUserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("smartApi.Entity.UserSession", b =>
                {
                    b.Property<Guid>("UserSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_session_id");

                    b.Property<string>("AuthenticationLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("PASSWORD_OTP")
                        .HasColumnName("authentication_level");

                    b.Property<string>("AuthenticationMethods")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("authentication_methods");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("LastActivityAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("LastIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("last_ip_address");

                    b.Property<string>("LastUserAgent")
                        .HasColumnType("text")
                        .HasColumnName("last_user_agent");

                    b.Property<DateTime?>("LoggedOutAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_out_at");

                    b.Property<DateTime>("LoginAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("login_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("LoginChallengeId")
                        .HasColumnType("uuid")
                        .HasColumnName("login_challenge_id");

                    b.Property<string>("LoginIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("login_ip_address");

                    b.Property<string>("LoginUserAgent")
                        .HasColumnType("text")
                        .HasColumnName("login_user_agent");

                    b.Property<string>("LogoutReason")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("logout_reason");

                    b.Property<bool>("OtpVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("otp_verified");

                    b.Property<DateTime?>("OtpVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("otp_verified_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedBy")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("revoked_by");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("revoked_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserDeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_device_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("UserSessionId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_user_sessions_expiry");

                    b.HasIndex("LastActivityAt")
                        .HasDatabaseName("idx_user_sessions_last_activity");

                    b.HasIndex("LoginChallengeId")
                        .IsUnique()
                        .HasDatabaseName("uq_user_sessions_login_challenge");

                    b.HasIndex("RevokedAt")
                        .HasDatabaseName("idx_user_sessions_revoked");

                    b.HasIndex("UserDeviceId", "Status")
                        .HasDatabaseName("idx_user_sessions_device_status");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("idx_user_sessions_user_expiry");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("idx_user_sessions_user_status");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("smartApi.Entity.email_otp_tokens", b =>
                {
                    b.Property<long>("EmailOtpTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("email_otp_token_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EmailOtpTokenId"));

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("LastSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sent_at");

                    b.Property<Guid?>("LoginChallengeId")
                        .HasColumnType("uuid")
                        .HasColumnName("login_challenge_id");

                    b.Property<int>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("max_attempts");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("purpose");

                    b.Property<int>("ResendCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("resend_count");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("revoked_reason");

                    b.Property<string>("SentToEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sent_to_email");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("EmailOtpTokenId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_email_otp_tokens_created_at");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_email_otp_tokens_expiry");

                    b.HasIndex("RevokedAt")
                        .HasDatabaseName("idx_email_otp_tokens_revoked_at");

                    b.HasIndex("SentToEmail")
                        .HasDatabaseName("idx_email_otp_tokens_sent_to_email");

                    b.HasIndex("LoginChallengeId", "Purpose")
                        .HasDatabaseName("ix_email_otp_tokens_challenge_id_purpose");

                    b.HasIndex("UserId", "Purpose", "ExpiresAt")
                        .HasDatabaseName("idx_email_otp_tokens_user_purpose_expiry");

                    b.HasIndex("UserId", "Purpose", "RevokedAt")
                        .HasDatabaseName("idx_email_otp_tokens_user_purpose_revoked");

                    b.HasIndex("UserId", "Purpose", "UsedAt")
                        .HasDatabaseName("idx_email_otp_tokens_lookup");

                    b.ToTable("email_otp_tokens", (string)null);
                });

            modelBuilder.Entity("smartApi.Entity.LoginActivity", b =>
                {
                    b.HasOne("smartApi.Entity.LoginChallenge", "LoginChallenge")
                        .WithMany("LoginActivities")
                        .HasForeignKey("LoginChallengeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("smartApi.Entity.UserDevice", "UserDevice")
                        .WithMany("LoginActivities")
                        .HasForeignKey("UserDeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("smartApi.Entity.User", "User")
                        .WithMany("LoginActivities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("smartApi.Entity.UserSession", "UserSession")
                        .WithMany("LoginActivities")
                        .HasForeignKey("UserSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LoginChallenge");

                    b.Navigation("User");

                    b.Navigation("UserDevice");

                    b.Navigation("UserSession");
                });

            modelBuilder.Entity("smartApi.Entity.LoginChallenge", b =>
                {
                    b.HasOne("smartApi.Entity.User", "User")
                        .WithMany("LoginChallenges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("smartApi.Entity.RefreshToken", b =>
                {
                    b.HasOne("smartApi.Entity.RefreshToken", "ReplacedByToken")
                        .WithMany("ReplacedTokens")
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("smartApi.Entity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smartApi.Entity.UserSession", "UserSession")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ReplacedByToken");

                    b.Navigation("User");

                    b.Navigation("UserSession");
                });

            modelBuilder.Entity("smartApi.Entity.UserCredential", b =>
                {
                    b.HasOne("smartApi.Entity.User", "User")
                        .WithOne("Credential")
                        .HasForeignKey("smartApi.Entity.UserCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("smartApi.Entity.UserDevice", b =>
                {
                    b.HasOne("smartApi.Entity.User", "User")
                        .WithMany("UserDevices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("smartApi.Entity.UserRole", b =>
                {
                    b.HasOne("smartApi.Entity.User", "AssignedByUser")
                        .WithMany("AssignedUserRoles")
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smartApi.Entity.User", "RevokedByUser")
                        .WithMany("RevokedUserRoles")
                        .HasForeignKey("RevokedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smartApi.Entity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smartApi.Entity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("RevokedByUser");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("smartApi.Entity.UserSession", b =>
                {
                    b.HasOne("smartApi.Entity.LoginChallenge", "LoginChallenge")
                        .WithOne("UserSession")
                        .HasForeignKey("smartApi.Entity.UserSession", "LoginChallengeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smartApi.Entity.UserDevice", "UserDevice")
                        .WithMany("UserSessions")
                        .HasForeignKey("UserDeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("smartApi.Entity.User", "User")
                        .WithMany("UserSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoginChallenge");

                    b.Navigation("User");

                    b.Navigation("UserDevice");
                });

            modelBuilder.Entity("smartApi.Entity.email_otp_tokens", b =>
                {
                    b.HasOne("smartApi.Entity.LoginChallenge", "LoginChallenge")
                        .WithMany("OtpTokens")
                        .HasForeignKey("LoginChallengeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smartApi.Entity.User", "User")
                        .WithMany("EmailOtpTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoginChallenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("smartApi.Entity.LoginChallenge", b =>
                {
                    b.Navigation("LoginActivities");

                    b.Navigation("OtpTokens");

                    b.Navigation("UserSession");
                });

            modelBuilder.Entity("smartApi.Entity.RefreshToken", b =>
                {
                    b.Navigation("ReplacedTokens");
                });

            modelBuilder.Entity("smartApi.Entity.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("smartApi.Entity.User", b =>
                {
                    b.Navigation("AssignedUserRoles");

                    b.Navigation("Credential");

                    b.Navigation("EmailOtpTokens");

                    b.Navigation("LoginActivities");

                    b.Navigation("LoginChallenges");

                    b.Navigation("RefreshTokens");

                    b.Navigation("RevokedUserRoles");

                    b.Navigation("UserDevices");

                    b.Navigation("UserRoles");

                    b.Navigation("UserSessions");
                });

            modelBuilder.Entity("smartApi.Entity.UserDevice", b =>
                {
                    b.Navigation("LoginActivities");

                    b.Navigation("UserSessions");
                });

            modelBuilder.Entity("smartApi.Entity.UserSession", b =>
                {
                    b.Navigation("LoginActivities");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
